Repository fun-eat/funeat-client, pull requests merged in 2024-06, with the labels that each got.

#131 refactor: 작성된 리뷰가 없는 경우 디자인 수정
  src/components/Review/ReviewList/ReviewList.tsx
  src/components/Review/ReviewList/reviewList.css.ts
  src/pages/ProductDetailPage/productDetailPage.css.ts
Labels: 🔧 Refactor, 🎨 UI

#137 fix: 태그 검색의 endpoint를 tagId로 변경
  src/components/Search/TagSearchResultList/TagSearchResultList.tsx
  src/constants/index.ts
  src/hooks/queries/search/useInfiniteProductSearchResultsQuery.ts
  src/hooks/search/useSearch.ts
  src/mocks/handlers/searchHandlers.ts
  src/pages/SearchPage/SearchPage.tsx
  src/pages/SearchPage/TagSearchResultPage.tsx
Labels: 🐛 Bug

#134 feat: 가이드 페이지 구현
  src/assets/onboarding-member.png
  src/assets/onboarding-recipe.png
  src/assets/onboarding-review.png
  src/components/Common/Stepper/Stepper.stories.tsx
  src/components/Common/Stepper/Stepper.tsx
  src/components/Common/Stepper/stepper.css.ts
  src/components/Common/Text/text.css.ts
  src/components/Common/index.ts
  src/constants/path.ts
  src/pages/OnboardingPage/OnboardingContent.tsx
  src/pages/OnboardingPage/OnboardingPage.tsx
  src/pages/OnboardingPage/onboardingPage.css.ts
  src/pages/ProductPage/ProductPage.tsx
  src/router/App.tsx
  src/router/index.tsx
Labels: ✨ Feature, 🎨 UI

#135 feat: 리뷰 랭킹 바텀시트 추가
  src/components/Rank/ReviewRankingList/ReviewRankingList.tsx
  src/components/Rank/ReviewRankingList/reviewRankingList.css.ts
  src/mocks/data/reviewRankingList.json
  src/pages/ReviewDetailPage.tsx
  src/router/index.tsx
  src/types/response.ts
Labels: ✨ Feature

#139 feat: 북마크 기능 구현
  src/components/Recipe/RecipeFavoriteButton/RecipeFavoriteButton.tsx
  src/hooks/queries/members/useInfiniteMemberRecipeBookmarkQuery.ts
  src/hooks/queries/recipe/index.ts
  src/hooks/queries/recipe/useRecipeBookmarkMutation.ts
  src/mocks/handlers/memberHandlers.ts
  src/mocks/handlers/recipeHandlers.ts
  src/types/recipe.ts
Labels: ✨ Feature

#147 refactor: MemberImage의 불필요한 alt 속성 삭제
  src/components/Review/BestReviewItem/BestReviewItem.tsx
  src/pages/RecipeDetailPage/RecipeDetailPage.tsx
Labels: 🔧 Refactor

#146 feat: 오늘의 리뷰 이미지 레이아웃 수정
  src/components/Rank/ReviewRankingItem/reviewRankingItem.css.ts
  src/components/Rank/ReviewRankingList/reviewRankingList.css.ts
  src/mocks/data/reviewRankingList.json
Labels: 🎨 UI

#145 fix: 카카오 로그인 버튼 에러 수정
  src/pages/LoginPage/LoginPage.tsx
Labels: 🐛 Bug

#149 fix: 가짜 로딩 제거
  src/index.tsx
Labels: 🐛 Bug

#155 refactor: any 제거
  src/components/Common/TabMenu/TabMenu.tsx
  src/types/common.ts
Labels: 🔧 Refactor

#157 fix: meta og image 버전 명시
  public/index.html
Labels: 🐛 Bug

#159 fix: 프로필 default 이미지 설정
  src/assets/product-notfound.png
  src/components/Product/ProductDetailItem/ProductDetailItem.tsx
  src/components/Product/ProductOverviewItem/ProductOverviewItem.tsx
  src/components/Review/ReviewItem/ReviewItem.tsx
  src/components/Review/ReviewItem/reviewItem.css.ts
  src/constants/image.ts
  src/mocks/data/recipes.json
  src/mocks/data/reviewRankingList.json
Labels: 🐛 Bug
