Repository fun-eat/funeat-client, pull requests merged in 2024-03, with the labels that each got.

#23 Vanilla extract 기본 셋팅
  .storybook/main.ts
  jest.config.js
  package.json
  public/index.html
  src/index.tsx
  src/styles/font.css.ts
  src/styles/font.ts
  src/styles/globalStyle.ts
  src/styles/index.css.ts
  src/styles/reset.css.ts
  webpack.common.js
  yarn.lock
Labels: ⚙️ Chore, 🔧 Refactor

#22 feat: 아이콘 추가
  .storybook/preview-body.html
  src/components/Common/NavigableSectionTitle/NavigableSectionTitle.tsx
  src/components/Common/NavigationBar/NavigationBar.tsx
  src/components/Common/ScrollButton/ScrollButton.tsx
  src/components/Common/SectionTitle/SectionTitle.tsx
  src/components/Common/SortButton/SortButton.tsx
  src/components/Common/Svg/SvgIcon.stories.tsx
  src/components/Common/Svg/SvgIcon.tsx
  src/components/Common/Svg/SvgSprite.tsx
  src/components/Members/MemberReviewItem/MemberReviewItem.tsx
  src/components/Members/MembersInfo/MembersInfo.tsx
  src/components/Product/ProductDetailItem/ProductDetailItem.tsx
  src/components/Product/ProductItem/ProductItem.tsx
  src/components/Rank/RecipeRankingItem/RecipeRankingItem.tsx
  src/components/Rank/ReviewRankingItem/ReviewRankingItem.tsx
  src/components/Recipe/CommentForm/CommentForm.tsx
  src/components/Recipe/RecipeFavoriteButton/RecipeFavoriteButton.tsx
  src/components/Recipe/RecipeItem/RecipeItem.tsx
  src/components/Recipe/RecipeRegisterForm/RecipeRegisterForm.tsx
  src/components/Review/BestReviewItem/BestReviewItem.tsx
  src/components/Review/ReviewFavoriteButton/ReviewFavoriteButton.tsx
  src/components/Review/ReviewItem/ReviewItem.tsx
  src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
  src/components/Review/StarRate/StarRate.tsx
  src/pages/HomePage.tsx
  src/pages/ReviewDetailPage.tsx
  src/pages/SearchPage.tsx
Labels: ✨ Feature, 🔧 Refactor

#30 refactor: 내비게이션바 개편
  src/components/Common/NavigationBar/NavigationBar.tsx
  src/components/Common/NavigationBar/navigationBar.css.ts
  src/constants/index.ts
  src/types/common.ts
Labels: 🔧 Refactor, 🎨 UI

#32 feat: 떠오르는 조합 구현
  .storybook/preview-body.html
  package.json
  src/components/Common/Svg/SvgIcon.tsx
  src/components/Common/Svg/SvgSprite.tsx
  src/components/Rank/RecipeRankingItem/RecipeRankingItem.stories.tsx
  src/components/Rank/RecipeRankingItem/RecipeRankingItem.tsx
  src/components/Rank/RecipeRankingItem/recipeRankingItem.css.ts
  src/components/Rank/RecipeRankingList/RecipeRankingList.stories.tsx
  src/components/Rank/RecipeRankingList/RecipeRankingList.tsx
  src/components/Rank/RecipeRankingList/recipeRankingList.css.ts
  src/components/Recipe/RecipeFavoriteButton/RecipeFavoriteButton.stories.tsx
  src/components/Recipe/RecipeFavoriteButton/RecipeFavoriteButton.tsx
  src/mocks/data/recipeRankingList.json
  src/types/ranking.ts
  yarn.lock
Labels: 🔧 Refactor, 🎨 UI

#29 feat: Section Header 구현
  .storybook/preview-body.html
  src/components/Common/SectionHeader/SectionHeader.stories.tsx
  src/components/Common/SectionHeader/SectionHeader.tsx
  src/components/Common/SectionHeader/sectionHeader.css.ts
  src/components/Common/Svg/SvgIcon.tsx
  src/components/Common/Svg/SvgSprite.tsx
  src/components/Common/index.ts
Labels: ✨ Feature, 🎨 UI

#33 feat: 상품 랭킹 구현
  src/components/Rank/ProductRankingItem/ProductRankingItem.stories.tsx
  src/components/Rank/ProductRankingItem/ProductRankingItem.tsx
  src/components/Rank/ProductRankingItem/productRankingItem.css.ts
  src/components/Rank/ProductRankingList/ProductRankingList.stories.tsx
  src/components/Rank/ProductRankingList/ProductRankingList.tsx
  src/components/Rank/ProductRankingList/productRankingList.css.ts
  src/components/Rank/index.ts
  src/mocks/data/productRankingList.json
  src/pages/HomePage.tsx
  src/types/ranking.ts
Labels: ✨ Feature, 🎨 UI

#31 feat: 오늘의 리뷰 섹션 구현
  src/components/Common/NavigationBar/NavigationBar.tsx
  src/components/Common/NavigationBar/navigationBar.css.ts
  src/components/Rank/ReviewRankingItem/ReviewRankingItem.stories.tsx
  src/components/Rank/ReviewRankingItem/ReviewRankingItem.tsx
  src/components/Rank/ReviewRankingItem/reviewRankingItem.css.ts
  src/components/Rank/ReviewRankingList/ReviewRankingList.tsx
  src/components/Rank/ReviewRankingList/reviewRankingList.css.ts
  src/constants/image.ts
  src/constants/index.ts
  src/mocks/data/reviewRankingList.json
  src/pages/HomePage.tsx
  src/types/ranking.ts
  src/types/response.ts
Labels: 🔧 Refactor, 🎨 UI

#34 feat: 홈화면 카테고리 섹션 스타일 개편
  src/components/Common/Banner/Banner.tsx
  src/components/Common/Banner/banner.css.ts
  src/components/Common/CategoryFoodList/CategoryFoodList.tsx
  src/components/Common/CategoryFoodList/categoryFoodList.css.ts
  src/components/Common/CategoryItem/CategoryItem.stories.tsx
  src/components/Common/CategoryItem/CategoryItem.tsx
  src/components/Common/CategoryItem/categoryItem.css.ts
  src/components/Common/CategoryStoreList/CategoryStoreList.tsx
  src/components/Common/CategoryStoreList/categoryStoreList.css.ts
  src/components/Common/Header/Header.tsx
  src/components/Common/Header/header.css.ts
  src/components/Common/SectionHeader/sectionHeader.css.ts
  src/components/Rank/ProductRankingList/ProductRankingList.tsx
  src/mocks/data/banners.json
  src/mocks/data/foodCategory.json
  src/mocks/data/storeCategory.json
  src/pages/HomePage.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/HomePage/homePage.css.ts
  src/router/index.tsx
Labels: ✨ Feature, 🎨 UI

#40 feat: 상품 둘러보기 리스트 구현
  .storybook/preview-body.html
  src/components/Common/Svg/SvgIcon.tsx
  src/components/Common/Svg/SvgSprite.tsx
  src/components/Product/ProductItem/ProductItem.tsx
  src/components/Product/ProductItem/productItem.css.ts
  src/components/Product/ProductPreviewList/ProductPreviewList.stories.tsx
  src/components/Product/ProductPreviewList/ProductPreviewList.tsx
  src/components/Product/ProductPreviewList/productPreviewList.css.ts
  src/components/Rank/ProductRankingItem/ProductRankingItem.tsx
  src/mocks/data/products.json
  src/types/product.ts
Labels: ✨ Feature, 🎨 UI

#46 feat: Page Header 구현
  .storybook/preview-body.html
  src/components/Common/PageHeader/PageHeader.stories.tsx
  src/components/Common/PageHeader/PageHeader.tsx
  src/components/Common/PageHeader/pageHeader.css.ts
  src/components/Common/Svg/SvgIcon.tsx
  src/components/Common/Svg/SvgSprite.tsx
Labels: ✨ Feature, 🎨 UI

#37 chore: 스토리북 배포
  .github/workflows/storybook.yml
  package.json
  src/components/Product/ProductList/ProductList.stories.tsx
  src/components/Recipe/CommentItem/CommentItem.stories.tsx
  src/components/Recipe/CommentList/CommentList.stories.tsx
  src/components/Recipe/RecipeList/RecipeList.stories.tsx
  src/components/Recipe/RecipeNameInput/RecipeNameInput.stories.tsx
  src/components/Review/BestReviewItem/BestReviewItem.stories.tsx
  src/components/Review/ReviewItem/ReviewItem.stories.tsx
  src/mocks/handlers/memberHandlers.ts
  yarn.lock
Labels: ⚙️ Chore

#51 refactor: 레이아웃 개편
  .storybook/preview-body.html
  src/components/Common/Header/Header.tsx
  src/components/Common/Header/header.css.ts
  src/components/Common/NavigationBar/NavigationBar.tsx
  src/components/Common/NavigationBar/navigationBar.css.ts
  src/components/Common/SectionHeader/sectionHeader.css.ts
  src/components/Common/Svg/SvgSprite.tsx
  src/components/Layout/DefaultLayout.tsx
  src/components/Layout/HeaderOnlyLayout.tsx
  src/components/Layout/MinimalLayout.tsx
  src/components/Layout/SimpleHeaderLayout.tsx
  src/components/Layout/index.ts
  src/components/Layout/layout.css.ts
  src/components/Rank/ProductRankingList/productRankingList.css.ts
  src/components/Rank/RecipeRankingList/recipeRankingList.css.ts
  src/components/Rank/ReviewRankingList/reviewRankingList.css.ts
  src/pages/HomePage/HomePage.tsx
  src/pages/HomePage/homePage.css.ts
  src/router/App.tsx
  src/router/index.tsx
  src/styles/font.css.ts
  src/styles/reset.css.ts
Labels: 🔧 Refactor, 🎨 UI

#50 refactor: 상품 페이지 개편
  __tests__/hooks/useTabMenu.test.ts
  package.json
  src/components/Common/CategoryFoodList/CategoryFoodList.tsx
  src/components/Common/CategoryFoodList/categoryFoodList.css.ts
  src/components/Common/CategoryFoodTab/CategoryFoodTab.stories.tsx
  src/components/Common/CategoryFoodTab/CategoryFoodTab.tsx
  src/components/Common/CategoryItem/CategoryItem.stories.tsx
  src/components/Common/CategoryItem/CategoryItem.tsx
  src/components/Common/CategoryItem/categoryItem.css.ts
  src/components/Common/CategoryStoreList/CategoryStoreList.tsx
  src/components/Common/CategoryStoreList/categoryStoreList.css.ts
  src/components/Common/CategoryStoreTab/CategoryStoreTab.stories.tsx
  src/components/Common/CategoryStoreTab/CategoryStoreTab.tsx
  src/components/Common/TabMenu/TabMenu.stories.tsx
  src/components/Common/TabMenu/TabMenu.tsx
  src/components/Common/TabMenu/tabMenu.css.ts
  src/components/Common/index.ts
  src/components/Product/ProductItem/ProductItem.tsx
  src/components/Product/ProductItem/productItem.css.ts
  src/components/Product/ProductPreviewList/productPreviewList.css.ts
  src/components/Product/index.ts
  src/components/Rank/ProductRankingItem/productRankingItem.css.ts
  src/constants/index.ts
  src/hooks/common/useTabMenu.ts
  src/hooks/queries/product/index.ts
  src/hooks/queries/product/useCategoryQuery.ts
  src/mocks/data/products.json
  src/pages/HomePage/HomePage.tsx
  src/pages/HomePage/homePage.css.ts
  src/pages/IntegratedSearchPage.tsx
  src/pages/ProductDetailPage.tsx
  src/pages/ProductListPage.tsx
  src/pages/ProductPage/ProductPage.tsx
  src/pages/ProductPage/productPage.css.ts
  src/router/index.tsx
  src/types/common.ts
  webpack.common.js
  yarn.lock
Labels: 🔧 Refactor, 🎨 UI

#52 feat: 플로팅 버튼 구현
  .storybook/preview-body.html
  public/mockServiceWorker.js
  src/components/Common/PageHeader/PageHeader.tsx
  src/components/Common/ScrollButton/ScrollButton.stories.tsx
  src/components/Common/ScrollButton/ScrollButton.tsx
  src/components/Common/ScrollButton/scrollButton.css.ts
  src/components/Common/Svg/SvgIcon.tsx
  src/components/Common/Svg/SvgSprite.tsx
  src/components/Common/WriteButton/WriteButton.stories.tsx
  src/components/Common/WriteButton/WriteButton.tsx
  src/components/Common/WriteButton/writeButton.css.ts
  src/pages/RecipePage.tsx
  yarn.lock
Labels: ✨ Feature, 🔧 Refactor, 🎨 UI

#58 feat: 검색페이지 마크업
  .storybook/preview-body.html
  package.json
  src/components/Common/Badge/Badge.stories.tsx
  src/components/Common/Badge/Badge.tsx
  src/components/Common/Badge/badge.css.ts
  src/components/Common/Header/Header.tsx
  src/components/Common/PageHeader/PageHeader.tsx
  src/components/Common/Svg/SvgIcon.tsx
  src/components/Common/Svg/SvgSprite.tsx
  src/components/Common/index.ts
  src/components/Product/ProductOverviewItem/ProductOverviewItem.stories.tsx
  src/components/Product/ProductOverviewItem/ProductOverviewItem.tsx
  src/components/Product/ProductOverviewItem/productOverviewItem.css.ts
  src/components/Product/ProductTitle/ProductTitle.tsx
  src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
  src/components/Search/ProductSearchResultList/ProductSearchResultList.tsx
  src/components/Search/ProductSearchResultList/productSearchResultList.css.ts
  src/components/Search/SearchInput/SearchInput.stories.tsx
  src/components/Search/SearchInput/SearchInput.tsx
  src/components/Search/SearchInput/searchInput.css.ts
  src/components/Search/index.ts
  src/constants/index.ts
  src/hooks/search/useSearch.ts
  src/pages/HomePage/HomePage.tsx
  src/pages/IntegratedSearchPage.tsx
  src/pages/RecipePage.tsx
  src/pages/SearchPage.tsx
  src/pages/SearchPage/SearchPage.tsx
  src/pages/SearchPage/searchPage.css.ts
  src/router/index.tsx
  src/utils/localStorage.ts
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
  yarn.lock
Labels: ✨ Feature, 🎨 UI

#57 feat: 상품 목록 페이지 구현
  .storybook/preview-body.html
  package.json
  src/components/Common/CategoryItem/CategoryItem.tsx
  src/components/Common/CategoryItem/categoryItem.css.ts
  src/components/Common/PageHeader/PageHeader.tsx
  src/components/Common/PageHeader/pageHeader.css.ts
  src/components/Common/SectionHeader/SectionHeader.tsx
  src/components/Common/SelectOptionList/SelectOptionList.stories.tsx
  src/components/Common/SelectOptionList/SelectOptionList.tsx
  src/components/Common/SelectOptionList/selectOptionList.css.ts
  src/components/Common/Svg/SvgIcon.tsx
  src/components/Common/Svg/SvgSprite.tsx
  src/components/Common/index.ts
  src/components/Product/ProductItem/ProductItem.tsx
  src/components/Product/ProductItem/productItem.css.ts
  src/components/Product/ProductList/ProductList.tsx
  src/components/Product/ProductList/productList.css.ts
  src/constants/index.ts
  src/hooks/common/index.ts
  src/hooks/common/useSelect.ts
  src/pages/ProductListPage/ProductListPage.tsx
  src/pages/ProductListPage/productListPage.css.ts
  src/pages/ProductPage/ProductPage.tsx
  src/router/index.tsx
  src/types/common.ts
  yarn.lock
Labels: ✨ Feature, 🎨 UI

#62 feat: 색상, 폰트 관련 글로벌 스타일 추가
  package.json
  src/components/Common/Text/Text.stories.tsx
  src/components/Common/Text/Text.tsx
  src/components/Common/Text/text.css.ts
  src/components/Common/Text/text.types.ts
  src/components/Common/index.ts
  src/styles/index.css.ts
  src/styles/theme.css.ts
  yarn.lock
Labels: ✨ Feature
