Repository fun-eat/funeat-client, pull requests merged in 2024-07, with the labels that each got.

#160 feat: 클라우드 프론트 캐시 무효화 로직 추가
  .github/workflows/deploy.yml
Labels: ✨ Feature, 🌎 Infra

#87 feat: Heading 컴포넌트 추가
  src/components/Common/CategoryItem/CategoryItem.tsx
  src/components/Common/ErrorBoundary/ErrorBoundary.tsx
  src/components/Common/ErrorComponent/ErrorComponent.tsx
  src/components/Common/ImageUploader/ImageUploader.tsx
  src/components/Common/StarRating/StarRating.tsx
  src/components/Common/TagList/TagList.tsx
  src/components/Common/Text/Text.tsx
  src/components/Common/TopBar/TopBar.tsx
  src/components/Common/Typography/Heading/Heading.stories.tsx
  src/components/Common/Typography/Heading/Heading.tsx
  src/components/Common/Typography/Text/Text.stories.tsx
  src/components/Common/Typography/Text/Text.tsx
  src/components/Common/Typography/typography.css.ts
  src/components/Common/Typography/typography.types.ts
  src/components/Common/index.ts
Labels: ✨ Feature

#162 refactor: 디자인 1차 수정
  src/assets/logo.svg
  src/components/Common/CategoryItem/CategoryItem.tsx
  src/components/Common/CategoryItem/categoryItem.css.ts
  src/components/Common/CategoryStoreList/CategoryStoreList.tsx
  src/components/Rank/ProductRankingItem/productRankingItem.css.ts
Labels: 🔧 Refactor, 🎨 UI
