Repository fun-eat/funeat-client, pull requests merged in 2024-04, with the labels that each got.

#70 fix: Text 컴포넌트가 p와 span 태그 둘 다 사용할 수 있게 수정
  src/components/Common/Text/Text.tsx
Labels: 🐛 Bug

#71 feat: 꿀조합 상세 페이지 디자인 마이그레이션
  .storybook/preview-body.html
  src/components/Common/SectionTitle/SectionTitle.stories.tsx
  src/components/Common/SectionTitle/SectionTitle.tsx
  src/components/Common/SectionTitle/sectionTitle.css.ts
  src/components/Common/Svg/SvgIcon.tsx
  src/components/Common/Svg/SvgSprite.tsx
  src/components/Product/ProductOverviewList/ProductOverviewList.tsx
  src/components/Recipe/CommentForm/CommentForm.tsx
  src/components/Recipe/CommentForm/commentForm.css.ts
  src/components/Recipe/CommentItem/CommentItem.stories.tsx
  src/components/Recipe/CommentItem/CommentItem.tsx
  src/components/Recipe/CommentItem/commentItem.css.ts
  src/components/Recipe/CommentList/CommentList.stories.tsx
  src/components/Recipe/CommentList/CommentList.tsx
  src/components/Recipe/CommentList/commentList.css.ts
  src/components/Recipe/RecipeFavoriteButton/RecipeFavoriteButton.tsx
  src/components/Recipe/RecipeFavoriteButton/recipeFavoriteButton.css.ts
  src/mocks/data/recipeDetail.json
  src/pages/ProductSearchListPage/ProductSearchListPage.tsx
  src/pages/RecipeDetailPage.tsx
  src/pages/RecipeDetailPage/RecipeDetailPage.tsx
  src/pages/RecipeDetailPage/recipeDetailPage.css.ts
  src/pages/ReviewDetailPage.tsx
  src/router/index.tsx
  src/styles/reset.css.ts
  src/types/recipe.ts
Labels: 🔧 Refactor

#75 feat: 상품 상세 페이지 개편
  src/components/Common/TagList/TagList.tsx
  src/components/Common/TagList/tagList.css.ts
  src/components/Common/Text/text.css.ts
  src/components/Common/Text/text.types.ts
  src/components/Product/ProductDetailItem/ProductDetailItem.stories.tsx
  src/components/Product/ProductDetailItem/ProductDetailItem.tsx
  src/components/Product/ProductDetailItem/productDetailItem.css.ts
  src/components/Product/ProductRecipeList/ProductRecipeList.tsx
  src/components/Product/ProductRecipeList/productRecipeList.css.ts
  src/components/Recipe/RecipeItem/RecipeItem.tsx
  src/components/Recipe/RecipeItem/recipeItem.css.ts
  src/components/Recipe/RecipeList/RecipeList.tsx
  src/components/Recipe/RecipeProductButton/RecipeProductButton.tsx
  src/components/Recipe/RecipeProductButton/recipeProductButton.css.ts
  src/components/Review/ReviewFavoriteButton/ReviewFavoriteButton.tsx
  src/components/Review/ReviewFavoriteButton/reviewFavoriteButton.css.ts
  src/components/Review/ReviewItem/ReviewItem.stories.tsx
  src/components/Review/ReviewItem/ReviewItem.tsx
  src/components/Review/ReviewItem/reviewItem.css.ts
  src/components/Review/ReviewList/ReviewList.tsx
  src/components/Review/ReviewList/reviewList.css.ts
  src/mocks/data/productDetail.json
  src/mocks/data/productDetails.json
  src/mocks/data/reviews.json
  src/pages/ProductDetailPage.tsx
  src/pages/ProductDetailPage/ProductDetailPage.tsx
  src/pages/ProductDetailPage/productDetailPage.css.ts
  src/router/index.tsx
  src/styles/theme.css.ts
  src/types/product.ts
Labels: ✨ Feature, 🎨 UI

#77 feat: 리뷰 작성 폼 개편
  .storybook/preview-body.html
  src/components/Common/ImageUploader/ImageUploader.tsx
  src/components/Common/ImageUploader/imageUploader.css.ts
  src/components/Common/Svg/SvgIcon.tsx
  src/components/Common/Svg/SvgSprite.tsx
  src/components/Review/RebuyCheckbox/RebuyCheckbox.tsx
  src/components/Review/RebuyCheckbox/rebuyCheckbox.css.ts
  src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
  src/components/Review/ReviewRegisterForm/ReviewTextarea/ReviewTextarea.stories.tsx
  src/components/Review/ReviewRegisterForm/ReviewTextarea/ReviewTextarea.tsx
  src/components/Review/ReviewRegisterForm/ReviewTextarea/reviewTextarea.css.ts
  src/components/Review/ReviewRegisterForm/StarRate/StarRate.stories.tsx
  src/components/Review/ReviewRegisterForm/StarRate/StarRate.tsx
  src/components/Review/ReviewRegisterForm/StarRate/starRate.css.ts
  src/components/Review/ReviewRegisterForm/reviewRegisterForm.css.ts
  src/components/Review/ReviewTagItem/ReviewTagItem.stories.tsx
  src/components/Review/ReviewTagItem/ReviewTagItem.tsx
  src/components/Review/ReviewTagList/ReviewTagList.tsx
  src/components/Review/ReviewTagList/reviewTagList.css.ts
  src/components/Review/ReviewTagSheet/ReviewTagSheet.stories.tsx
  src/components/Review/ReviewTagSheet/ReviewTagSheet.tsx
  src/components/Review/ReviewTagSheet/reviewTagSheet.css.ts
  src/components/Review/ReviewTextarea/ReviewTextarea.tsx
  src/components/Review/index.ts
  src/constants/index.ts
  src/contexts/ReviewFormContext.tsx
  src/pages/ReviewRegisterPage/ReviewRegisterPage.tsx
  src/pages/ReviewRegisterPage/reviewRegisterPage.css.ts
  src/router/index.tsx
Labels: ✨ Feature, 🎨 UI

#83 refactor: 기초 recipe item 컴포넌트 구현
  src/components/Members/MemberRecipeList/MemberRecipeList.tsx
  src/components/Product/ProductRecipeList/ProductRecipeList.tsx
  src/components/Rank/RecipeRankingItem/RecipeRankingItem.stories.tsx
  src/components/Rank/RecipeRankingItem/RecipeRankingItem.tsx
  src/components/Rank/RecipeRankingItem/recipeRankingItem.css.ts
  src/components/Rank/RecipeRankingList/RecipeRankingList.tsx
  src/components/Rank/index.ts
  src/components/Recipe/RecipeFavoriteButton/recipeFavoriteButton.css.ts
  src/components/Recipe/RecipeItem/RecipeItem.stories.tsx
  src/components/Recipe/RecipeItem/RecipeItem.tsx
  src/components/Recipe/RecipeItem/recipeItem.css.ts
  src/components/Recipe/RecipeList/RecipeList.tsx
  src/components/Recipe/index.ts
  src/constants/image.ts
  src/contexts/RecipeItemContext.tsx
  src/hooks/context/index.ts
  src/hooks/context/useRecipeItemValueContext.ts
  src/mocks/data/recipeRankingList.json
  src/mocks/data/recipes.json
  src/types/ranking.ts
  src/types/recipe.ts
  src/types/response.ts
Labels: 🔧 Refactor

#93 feat: 꿀조합 등록 버튼 스타일 수정
  src/components/Recipe/CommentForm/CommentForm.tsx
  src/components/Recipe/CommentForm/commentForm.css.ts
  src/components/Recipe/RecipeFavoriteButton/recipeFavoriteButton.css.ts
Labels: 🎨 UI

#91 feat: 꿀조합 검색 디자인 변경점 적용
  src/components/Common/ShowAllButton/ShowAllButton.tsx
  src/components/Common/ShowAllButton/showAllButton.css.ts
  src/components/Common/index.ts
  src/components/Product/ProductRecipeList/ProductRecipeList.tsx
  src/components/Product/ProductRecipeList/productRecipeList.css.ts
  src/components/Recipe/RecipeItem/RecipeItem.tsx
  src/components/Search/ProductSearchResultPreviewList/ProductSearchResultPreviewList.stories.tsx
  src/components/Search/ProductSearchResultPreviewList/ProductSearchResultPreviewList.tsx
  src/components/Search/ProductSearchResultPreviewList/productSearchResultPreivewList.css.ts
  src/components/Search/RecipeSearchResultPreviewList/RecipeSearchResultPreviewList.tsx
  src/components/Search/RecipeSearchResultPreviewList/recipeSearchResultPreviewList.css.ts
  src/components/Search/index.ts
  src/pages/ProductDetailPage/ProductDetailPage.tsx
  src/pages/ProductSearchListPage/ProductSearchListPage.tsx
  src/pages/RecipeSearchListPage/RecipeSearchListPage.tsx
  src/pages/RecipeSearchListPage/recipeSearchListPage.css.ts
  src/pages/SearchPage/SearchPage.tsx
  src/router/index.tsx
Labels: 🔧 Refactor

#89 feat: 상품 리뷰 작성 구현
  src/components/Common/TopBar/TopBar.stories.tsx
  src/components/Common/TopBar/TopBar.tsx
  src/components/Common/TopBar/topBar.css.ts
  src/components/Product/ProductRecipeList/ProductRecipeList.tsx
  src/components/Product/ProductRecipeList/productRecipeList.css.ts
  src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
  src/components/Review/ReviewRegisterForm/reviewRegisterForm.css.ts
  src/components/Review/ReviewTagList/ReviewTagList.tsx
  src/components/Review/ReviewTagSheet/ReviewTagSheet.tsx
  src/components/Review/ReviewTagSheet/reviewTagSheet.css.ts
  src/components/Search/SearchNotFound/SearchNotFound.tsx
  src/contexts/ReviewFormContext.tsx
  src/hooks/queries/product/useInfiniteProductReviewsQuery.ts
  src/mocks/handlers/reviewHandlers.ts
  src/pages/ProductDetailPage/ProductDetailPage.tsx
  src/pages/ProductDetailPage/productDetailPage.css.ts
  src/pages/ReviewRegisterPage/ReviewRegisterPage.tsx
  src/pages/ReviewRegisterPage/reviewRegisterPage.css.ts
  src/router/index.tsx
Labels: ✨ Feature

#99 feat: 상품 페이지 디자인 변경점 적용
  src/components/Common/CategoryFoodList/CategoryFoodList.tsx
  src/components/Common/CategoryFoodList/categoryFoodList.css.ts
  src/components/Common/CategoryItem/CategoryItem.tsx
  src/components/Common/CategoryItem/categoryItem.css.ts
  src/components/Common/CategoryStoreList/CategoryStoreList.tsx
  src/components/Common/CategoryStoreList/categoryStoreList.css.ts
  src/components/Common/SectionHeader/SectionHeader.tsx
  src/components/Common/SectionHeader/sectionHeader.css.ts
  src/mocks/data/foodCategory.json
  src/mocks/data/storeCategory.json
  src/pages/ProductPage/ProductPage.tsx
  src/pages/ProductPage/productPage.css.ts
Labels: 🎨 UI

#56 feat: 오늘의 리뷰 태그 스타일 수정
  src/components/Members/MemberRecipeList/MemberRecipeList.tsx
  src/components/Members/MemberReviewList/MemberReviewList.tsx
  src/components/Product/ProductPreviewList/ProductPreviewList.tsx
  src/components/Rank/ReviewRankingItem/ReviewRankingItem.stories.tsx
  src/components/Rank/ReviewRankingItem/ReviewRankingItem.tsx
  src/components/Rank/ReviewRankingItem/reviewRankingItem.css.ts
  src/components/Rank/ReviewRankingList/ReviewRankingList.tsx
  src/components/Rank/ReviewRankingList/reviewRankingList.css.ts
  src/mocks/data/reviewRankingList.json
  src/mocks/data/reviewTagList.json
Labels: ✨ Feature, 🎨 UI

#103 refactor: 로고 및 파비콘 교체
  public/assets/apple-icon-180x180.png
  public/assets/favicon-16x16.png
  public/assets/favicon-32x32.png
  public/assets/favicon.ico
  src/assets/logo.svg
  src/components/Common/Header/Header.tsx
  src/components/Common/Header/header.css.ts
  src/components/Common/TopBar/TopBar.tsx
  src/pages/LoginPage.tsx
Labels: 🔧 Refactor

#106 fix: item image 규격 맞지 않는 부분 수정
  src/components/Product/ProductItem/ProductItem.tsx
  src/components/Product/ProductItem/productItem.css.ts
  src/components/Product/ProductList/productList.css.ts
  src/components/Product/ProductPreviewList/ProductPreviewList.tsx
  src/components/Product/ProductPreviewList/productPreviewList.css.ts
  src/components/Rank/RecipeRankingList/recipeRankingList.css.ts
  src/components/Rank/ReviewRankingItem/ReviewRankingItem.tsx
  src/components/Rank/ReviewRankingItem/reviewRankingItem.css.ts
  src/components/Rank/ReviewRankingList/ReviewRankingList.tsx
  src/components/Rank/ReviewRankingList/reviewRankingList.css.ts
  src/components/Recipe/RecipeItem/RecipeItem.tsx
  src/components/Recipe/RecipeItem/recipeItem.css.ts
  src/components/Recipe/RecipeList/recipeList.css.ts
  src/mocks/data/products.json
  src/mocks/data/recipes.json
  src/mocks/data/reviewRankingList.json
  src/styles/common.css.ts
Labels: 🐛 Bug, 🎨 UI

#115 fix: 뒤로가기 버튼 동작 수정
  src/components/Common/TopBar/TopBar.tsx
  src/pages/ProductDetailPage/ProductDetailPage.tsx
  src/pages/ProductListPage/ProductListPage.tsx
Labels: 🐛 Bug

#109 fix: 오늘의 리뷰 레이아웃 깨짐현상 해결
  src/components/Rank/ReviewRankingList/reviewRankingList.css.ts
Labels: 🐛 Bug, 🎨 UI

#113 fix: 스켈레톤 위치 수정
  src/components/Product/ProductItem/ProductItem.tsx
  src/components/Product/ProductItem/productItem.css.ts
  src/components/Recipe/RecipeItem/RecipeItem.tsx
  src/components/Recipe/RecipeItem/recipeItem.css.ts
Labels: 🐛 Bug, 🎨 UI

#117 feat: 상품 목록 배너 추가
  src/constants/image.ts
  src/pages/ProductPage/ProductPage.tsx
Labels: ✨ Feature, 🎨 UI

#95 feat: 마이페이지 구현
  .storybook/preview-body.html
  src/assets/defaultProfile.png
  src/components/Common/SectionHeader/sectionHeader.css.ts
  src/components/Common/StarRating/StarRating.stories.tsx
  src/components/Common/StarRating/StarRating.tsx
  src/components/Common/StarRating/starRating.css.ts
  src/components/Common/Svg/SvgSprite.tsx
  src/components/Common/TopBar/TopBar.tsx
  src/components/Common/TopBar/topBar.css.ts
  src/components/Common/index.ts
  src/components/Members/MemberImage/MemberImage.tsx
  src/components/Members/MemberImage/memberImage.css.ts
  src/components/Members/MemberModifyInput/MemberModifyInput.stories.tsx
  src/components/Members/MemberModifyInput/MemberModifyInput.tsx
  src/components/Members/MemberModifyInput/memberModifyInput.css.ts
  src/components/Members/MemberRecipeList/MemberRecipeList.tsx
  src/components/Members/MemberRecipeList/memberRecipeList.css.ts
  src/components/Members/MemberReviewItem/MemberReviewItem.stories.tsx
  src/components/Members/MemberReviewItem/MemberReviewItem.tsx
  src/components/Members/MemberReviewItem/memberReviewItem.css.ts
  src/components/Members/MemberReviewList/MemberReviewList.tsx
  src/components/Members/MembersInfo/MemberInfo.stories.tsx
  src/components/Members/MembersInfo/MembersInfo.tsx
  src/components/Members/MembersInfo/memberInfo.css.ts
  src/components/Members/PostCounterBox/PostCounterBox.stories.tsx
  src/components/Members/PostCounterBox/PostCounterBox.tsx
  src/components/Members/PostCounterBox/postCounterBox.css.ts
  src/components/Members/index.ts
  src/components/Recipe/CommentForm/CommentForm.tsx
  src/components/Review/ReviewItem/ReviewItem.tsx
  src/components/Review/ReviewItem/reviewItem.css.ts
  src/components/Review/ReviewItemInfo/ReviewItemInfo.stories.tsx
  src/components/Review/ReviewItemInfo/ReviewItemInfo.tsx
  src/components/Review/ReviewItemInfo/reviewItemInfo.css.ts
  src/components/Review/index.ts
  src/components/Search/SearchInput/searchInput.css.ts
  src/constants/index.ts
  src/mocks/data/memberRecipes.json
  src/mocks/data/memberReviews.json
  src/mocks/data/members.json
  src/mocks/handlers/memberHandlers.ts
  src/pages/MemberModifyPage.tsx
  src/pages/MemberModifyPage/MemberModifyPage.tsx
  src/pages/MemberModifyPage/memberModifyPage.css.ts
  src/pages/MemberPage.tsx
  src/pages/MemberPage/MemberPage.tsx
  src/pages/MemberPage/memberPage.css.ts
  src/pages/MemberPostPage/MemberPostPage.tsx
  src/pages/MemberRecipePage.tsx
  src/pages/MemberReviewPage.tsx
  src/pages/ProductPage/ProductPage.tsx
  src/router/index.tsx
  src/types/common.ts
  src/types/member.ts
  src/types/recipe.ts
  src/types/response.ts
  src/types/review.ts
  webpack.common.js
Labels: ✨ Feature, 🔧 Refactor, 🎨 UI

#120 fix: 조합실 리스트 grid 레이아웃 깨지는 오류 해결
  src/components/Recipe/RecipeList/recipeList.css.ts
Labels: 🐛 Bug, 🎨 UI

#122 feat: 오늘의 리뷰 이미지 없는 경우 처리
  src/components/Rank/ReviewRankingItem/ReviewRankingItem.tsx
  src/mocks/data/reviewRankingList.json
Labels: 🎨 UI
